name: Update CE Application

on: [push]

# Environment variables available to all jobs and steps in this workflow
env:
  GITHUB_SHA: ${{ github.sha }}
  IBM_CLOUD_API_KEY: ${{ secrets.REGISTRY_PASSWORD }}
  IBM_CLOUD_REGION: us-south
  IBM_CLOUD_RESOURCE_GROUP: 2022-cde-lab
  ICR_NAMESPACE: rtiffany
  REGISTRY_HOSTNAME: us.icr.io
  IMAGE_NAME: mkdocs-caddy
  CODE_ENGINE_PROJECT: cde-dev-guides
  CODE_ENGINE_APP: caddy-mkdocs-app-v1


jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    # Download and Install IBM Cloud CLI
    - name: Install IBM Cloud CLI
      run: |
        curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
        ibmcloud --version
        ibmcloud config --check-version=false
        ibmcloud plugin install -f code-engine
        ibmcloud plugin install -f container-registry 
    # Authenticate with IBM Cloud CLI
    - name: Authenticate with IBM Cloud CLI
      run: |
        ibmcloud login -r ${{ env.IBM_CLOUD_REGION }} --apikey ${{ env.IBM_CLOUD_API_KEY }} 
        ibmcloud target -g ${{ env.IBM_CLOUD_RESOURCE_GROUP }}
        ibmcloud cr region-set ${{ env.IBM_CLOUD_REGION }}
        ibmcloud cr login
    
    - name: Target Code Engine project 
      run: |
        ibmcloud code-engine project target --name ${{ env.CODE_ENGINE_PROJECT }}
        ibmcloud code-engine app update --name ${{ env.CODE_ENGINE_APP }} --build-source https://github.com/${{ github.repository }}" --image "${REGISTRY_HOSTNAME}"/"${ICR_NAMESPACE}"/"${IMAGE_NAME}":"${GITHUB_SHA}" --registry-secret new-rs --port http1:80

